version: '2.16'

services:
  api:
    image: yom-backend
    container_name: yom-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    restart: unless-stopped
    depends_on:
      - db1
      - db2

  db1:
    image: postgres:15.2-alpine
    container_name: yom-db-development
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - .db1-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yom-db-development

  db2:
    image: postgres:15.2-alpine
    container_name: yom-db-tests
    restart: unless-stopped
    ports:
      - '5433:5432'
    volumes:
      - .db2-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yom-db-tests

volumes:
  db1-data:
  db2-data:
