apiVersion: v1
kind: Service
metadata:
  name: topology-inventory
  labels:
    app: topology-inventory
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app: topology-inventory
